<script>
export default{data(){return{period:'月度',periods:['周度','月度','年度'],bars:[42,58,51,72,66,84,76,91,78,88,94,86]}}}
</script>
<template><div class="page-wrap">
 <p class="eyebrow">Personal Metrics</p><h1 class="page-title">数据观察室</h1><p class="page-lead">把抽象的变化变成清晰的趋势。以下是个人站点与内容表现的演示数据。</p>
 <div class="metric-grid"><article><span>总访问量</span><strong>28,640</strong><i>↗ 12.8%</i></article><article><span>文章阅读</span><strong>16,892</strong><i>↗ 8.4%</i></article><article><span>平均停留</span><strong>04:26</strong><i>↗ 18.2%</i></article><article><span>收藏总数</span><strong>1,284</strong><i>↗ 6.7%</i></article></div>
 <div class="dash-grid"><section class="chart-card"><div class="card-head"><div><span>访问趋势</span><h2>持续生长的数字足迹</h2></div><div><button v-for="p in periods" :class="{active:period===p}" @click="period=p">{{p}}</button></div></div><div class="chart"><div v-for="(b,i) in bars" class="bar" :style="{height:(period==='年度'?b:period==='周度'?Math.max(28,b-18):b)+'%'}"><span>{{['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'][i]}}</span></div></div></section>
 <section class="donut-card"><span>内容构成</span><div class="donut"><b>42%</b><small>技术内容</small></div><ul><li><i style="background:#174f42"></i>技术手记 <b>42%</b></li><li><i style="background:#c8f560"></i>生活随笔 <b>31%</b></li><li><i style="background:#ef7354"></i>成长思考 <b>27%</b></li></ul></section></div>
 <div class="insights"><div><span class="eyebrow">Insight 01</span><h3>周二晚间，是读者最活跃的时间</h3></div><div><span class="eyebrow">Insight 02</span><h3>深度长文的收藏率高出平均值 2.4 倍</h3></div><div><span class="eyebrow">Insight 03</span><h3>移动端贡献了 68% 的阅读访问</h3></div></div>
</div></template>
<style scoped>
.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:42px 0 16px}.metric-grid article,.chart-card,.donut-card{background:var(--paper);border:1px solid var(--line);border-radius:18px;padding:24px}.metric-grid span,.donut-card>span{font-size:12px;color:var(--muted)}.metric-grid strong{font:34px Georgia;display:block;margin:14px 0 8px}.metric-grid i{font-style:normal;font-size:12px;color:var(--green)}.dash-grid{display:grid;grid-template-columns:1fr 310px;gap:16px}.card-head{display:flex;justify-content:space-between}.card-head span{font-size:12px;color:var(--muted)}.card-head h2{font:25px Georgia;margin:7px 0}.card-head button{border:0;background:none;padding:7px 9px;border-radius:8px;font-size:11px;cursor:pointer}.card-head button.active{background:var(--green);color:white}.chart{height:270px;border-bottom:1px solid var(--line);display:flex;gap:10px;align-items:end;padding-top:35px}.bar{flex:1;background:var(--green);border-radius:5px 5px 0 0;position:relative;min-height:20px;transition:.5s}.bar:nth-child(3n){background:var(--lime)}.bar span{position:absolute;bottom:-24px;font-size:9px;color:var(--muted);white-space:nowrap}.donut{width:170px;height:170px;border-radius:50%;margin:28px auto;background:conic-gradient(var(--green) 0 42%,var(--lime) 42% 73%,#ef7354 73%);position:relative;display:grid;place-content:center;text-align:center}.donut:before{content:"";position:absolute;inset:28px;background:var(--paper);border-radius:50%}.donut b,.donut small{z-index:1}.donut b{font:30px Georgia}.donut small{color:var(--muted)}ul{list-style:none;padding:0}li{display:flex;align-items:center;gap:8px;font-size:12px;margin:12px 0}li i{width:8px;height:8px;border-radius:50%}li b{margin-left:auto}.insights{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:16px}.insights>div{border-top:3px solid var(--ink);padding:20px 8px}.insights h3{font:19px/1.5 Georgia,"Songti SC"}
@media(max-width:800px){.metric-grid{grid-template-columns:1fr 1fr}.dash-grid{grid-template-columns:1fr}.insights{grid-template-columns:1fr}.chart-card{overflow:hidden}}
</style>
