-- App 字节码插装事件。客户端只通过 Edge Function 写入，登录用户可在看板读取。
create table if not exists public.app_telemetry_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (
    event_type in ('startup', 'method', 'page_resume', 'page_pause', 'click', 'block', 'aop_enter', 'aop_exit')
  ),
  event_time timestamptz not null,
  received_at timestamptz not null default now(),
  app_id text not null default 'com.example.mystudy',
  app_version text,
  build_type text,
  platform text not null default 'android',
  device_id text,
  session_id text,
  batch_id uuid,
  page text,
  method text,
  view_type text,
  view_id text,
  cost_ms double precision,
  tag text,
  permission text,
  allowed boolean,
  metadata jsonb not null default '{}'::jsonb,
  constraint app_telemetry_event_time_sane check (
    event_time >= timestamptz '2020-01-01 00:00:00+00'
    and event_time <= now() + interval '1 day'
  ),
  constraint app_telemetry_cost_nonnegative check (cost_ms is null or cost_ms >= 0)
);

create index if not exists app_telemetry_events_time_idx
  on public.app_telemetry_events (event_time desc);
create index if not exists app_telemetry_events_app_type_time_idx
  on public.app_telemetry_events (app_id, event_type, event_time desc);
create index if not exists app_telemetry_events_device_time_idx
  on public.app_telemetry_events (device_id, event_time desc)
  where device_id is not null;
create unique index if not exists app_telemetry_events_batch_event_idx
  on public.app_telemetry_events (batch_id, (metadata ->> 'eventId'))
  where batch_id is not null and metadata ? 'eventId';

alter table public.app_telemetry_events enable row level security;

drop policy if exists "authenticated users can read app telemetry" on public.app_telemetry_events;
create policy "authenticated users can read app telemetry"
  on public.app_telemetry_events for select to authenticated using (true);

comment on table public.app_telemetry_events is
  'Android ASM instrumentation events received by the app-events Edge Function.';
